In [1]:
import numpy as np

In [3]:
a = np.array([[1, 3], [2, 0]])

In [4]:
b = np.array([[3],[1]])

In [5]:
c = np.array([[2, 1, 5],[1, 0, 3],[1,1,1]])

In [6]:
d = np.array([[0, 1],[3,0],[1,1]])

In [8]:
a*b

array([[3, 9],
       [2, 0]])

In [9]:
a*c

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [10]:
a*d

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [11]:
b*c

ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 

In [12]:
c*d

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [13]:
d*c

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [14]:
d*a

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [15]:
b*d

ValueError: operands could not be broadcast together with shapes (2,1) (3,2) 

In [16]:
a = np.array([[1, 1], [1, 1], [1, -1]])

In [17]:
u, s, vh = np.linalg.svd(a)

In [23]:
print(u,"\n", s,"\n",vh)

[[-7.07106781e-01 -2.22044605e-16 -7.07106781e-01]
 [-7.07106781e-01 -1.11022302e-16  7.07106781e-01]
 [-5.55111512e-17  1.00000000e+00 -2.25745422e-16]] 
 [2.         1.41421356] 
 [[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


In [25]:
r1_aprox = u[1]

[[ 1  1]
 [ 1  1]
 [ 1 -1]]


In [48]:
u[0:2,0] @ vh[0]

0.9999999999999999

array([-0.70710678, -0.70710678])